print("Find your spirit name. Answer a few questions and get your spirit name")
animal = input("What's your favorite animal\n")
color = input("what color is your shirt\n")
desk = input("final question. Using only 1 word, describe your desk\n")
print ("Your spirit name is "+desk + " " + color + " " + animal)